export const locales = ["en", "ar"] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => value === "en" || value === "ar";
export const pick = (locale: Locale, en: string, ar: string) => locale === "ar" ? ar : en;

export const copy = {
  en: {
    nav: { properties: "Properties", developments: "Developments", areas: "Areas", about: "About", contact: "Contact" },
    common: { explore: "Explore properties", viewProperty: "View property", viewDevelopment: "Explore development", viewArea: "Explore area", allProperties: "All properties", allDevelopments: "All developments", allAreas: "All areas", requestViewing: "Request a viewing", whatsapp: "WhatsApp us", talkAdvisor: "Talk to an advisor", from: "From", startingFrom: "Starting from", beds: "Beds", bathrooms: "Bathrooms", builtUp: "m² built-up", land: "m² land", delivery: "Delivery", propertyCode: "Property code", clearAll: "Clear all", applyFilters: "Apply filters", close: "Close", noResults: "No properties match these filters.", resetFilters: "Reset filters", illustrative: "Illustrative concept data", demo: "DEMONSTRATION LISTING", viewAll: "View all", back: "Back" },
    hero: { eyebrow: "VANTA ESTATES / EGYPT", title1: "Find your", title2: "next address.", description: "A clearer way to discover exceptional homes, places, and possibilities across Egypt.", imageLabel: "NEW CAIRO", searchLabel: "Start your search", searchAction: "Explore properties", discover: "Discover places", scroll: "SCROLL TO EXPLORE" },
    search: { location: "Location", type: "Property type", budget: "Budget", bedrooms: "Bedrooms", delivery: "Delivery", developer: "Developer", anyLocation: "All locations", anyType: "All types", anyBudget: "Any budget", anyBedrooms: "Any bedrooms", anyDelivery: "Any delivery", anyDeveloper: "All developers", under5: "Under 5M", fiveTen: "5–10M", tenTwenty: "10–20M", overTwenty: "20M+", filters: "Filters", sort: "Sort by", featured: "Featured", lowHigh: "Price: low to high", highLow: "Price: high to low", newest: "Newest", grid: "Grid view", list: "List view" },
    home: { featuredEyebrow: "01 / CURATED COLLECTION", featuredTitle: "Curated for where life is going.", featuredIntro: "Homes and spaces selected for location, utility, and what comes next.", areaEyebrow: "02 / CITY ATLAS", areaTitle: "Explore by place.", areaIntro: "Start with the neighborhood. See the opportunities around it.", developmentsEyebrow: "03 / DEVELOPMENTS", developmentsTitle: "Places with a bigger plan.", storyEyebrow: "FEATURED DEVELOPMENT", storyTitle: "A city within the city.", smartEyebrow: "04 / FIND YOUR FIT", smartTitle: "Not sure where to start?", smartIntro: "Three quick choices will narrow the collection.", whyEyebrow: "THE VANTA APPROACH", whyTitle: "Property decisions need clarity.", ctaTitle1: "A property can look right.", ctaTitle2: "Seeing it makes the difference.", ctaText: "Move from discovery to a conversation, then to the space itself." },
    smart: { purpose: "What are you buying for?", live: "To live", invest: "To invest", budget: "Your budget?", where: "Where?", east: "East Cairo", west: "West Cairo", coastal: "Coastal", matches: "matching properties", showMatches: "See matching properties", select: "Choose one" },
    why: [ { title: "MARKET CLARITY", text: "Properties presented with the information that matters." }, { title: "DIRECT ACCESS", text: "Speak directly with an advisor through a simple handoff." }, { title: "CURATED OPTIONS", text: "Less noise. Better choices." }, { title: "VIEWING FIRST", text: "Move from browsing to a viewing request quickly." } ],
    pages: { properties: "Properties", propertiesIntro: "Curated opportunities across Egypt's most compelling addresses.", developments: "Developments", developmentsIntro: "Districts and communities with a clear point of view.", areas: "The area atlas", areasIntro: "Compare places before you compare properties.", about: "Property decisions need clarity.", aboutIntro: "VANTA is a concept for a more legible property journey: discover, compare, visit, decide.", contact: "Let's find the right next step.", contactIntro: "Tell us what you are looking for. This demonstration prepares a WhatsApp inquiry for an advisor.", found: "opportunities found", featured: "Featured collection" },
    detail: { overview: "Overview", amenities: "Amenities", payment: "Payment plan", location: "Location intelligence", floor: "Floor plan", related: "You may also like", interested: "Interested in this property?", inquiryIntro: "Share your details to prepare a WhatsApp viewing request.", name: "Your name", phone: "Phone number", date: "Preferred date", send: "Continue to WhatsApp", call: "Call", gallery: "View all 8 photos", imageNote: "Concept imagery for demonstration", planNote: "Illustrative floor plan — not to scale", nearby: "Illustrative travel times", ground: "Ground", first: "First", roof: "Roof", galleryTitle: "Property gallery", viewingNote: "No request is stored on this demo website." },
    about: { steps: [ ["Discover", "Find places and homes that fit your direction."], ["Compare", "Put price, size, location, and delivery side by side."], ["Visit", "See the space and ask the questions that matter."], ["Decide", "Move forward with a clearer picture."] ], statement: "A better property journey starts with better information.", note: "This is a fictional brand and a demonstration of a real estate marketing experience." },
    footer: { line: "The next address starts here.", navigate: "Navigate", connect: "Connect", location: "Based in", coordinates: "CAIRO COORDINATES", disclaimer: "A demonstration website created to showcase design and development. Properties, prices and developments shown are illustrative and are not real listings.", rights: "Concept website. All listing data is fictional." },
  },
  ar: {
    nav: { properties: "العقارات", developments: "المشروعات", areas: "المناطق", about: "عن فانتا", contact: "تواصل معنا" },
    common: { explore: "استكشف العقارات", viewProperty: "عرض العقار", viewDevelopment: "استكشف المشروع", viewArea: "استكشف المنطقة", allProperties: "كل العقارات", allDevelopments: "كل المشروعات", allAreas: "كل المناطق", requestViewing: "اطلب معاينة", whatsapp: "تواصل عبر واتساب", talkAdvisor: "تحدث إلى مستشار", from: "من", startingFrom: "يبدأ من", beds: "غرف", bathrooms: "حمامات", builtUp: "م² مباني", land: "م² أرض", delivery: "التسليم", propertyCode: "كود العقار", clearAll: "مسح الكل", applyFilters: "تطبيق الفلاتر", close: "إغلاق", noResults: "لا توجد عقارات تطابق هذه الفلاتر.", resetFilters: "إعادة ضبط الفلاتر", illustrative: "بيانات توضيحية", demo: "عقار تجريبي", viewAll: "عرض الكل", back: "رجوع" },
    hero: { eyebrow: "فانتا العقارية / مصر", title1: "اعثر على", title2: "عنوانك القادم.", description: "طريقة أوضح لاكتشاف منازل وأماكن وفرص مميزة في أنحاء مصر.", imageLabel: "القاهرة الجديدة", searchLabel: "ابدأ البحث", searchAction: "استكشف العقارات", discover: "اكتشف المناطق", scroll: "مرر للاستكشاف" },
    search: { location: "المنطقة", type: "نوع العقار", budget: "الميزانية", bedrooms: "غرف النوم", delivery: "التسليم", developer: "المطور", anyLocation: "كل المناطق", anyType: "كل الأنواع", anyBudget: "أي ميزانية", anyBedrooms: "أي عدد غرف", anyDelivery: "أي موعد", anyDeveloper: "كل المطورين", under5: "أقل من ٥ مليون", fiveTen: "٥–١٠ مليون", tenTwenty: "١٠–٢٠ مليون", overTwenty: "٢٠ مليون+", filters: "الفلاتر", sort: "الترتيب", featured: "المميز", lowHigh: "السعر: الأقل أولاً", highLow: "السعر: الأعلى أولاً", newest: "الأحدث", grid: "عرض شبكي", list: "عرض قائمة" },
    home: { featuredEyebrow: "٠١ / مجموعة مختارة", featuredTitle: "اختيارات تناسب خطوتك القادمة.", featuredIntro: "منازل ومساحات مختارة للموقع والعملية وما ينتظرك بعد ذلك.", areaEyebrow: "٠٢ / أطلس المدن", areaTitle: "ابدأ من المكان.", areaIntro: "ابدأ بالحي، ثم اكتشف الفرص من حوله.", developmentsEyebrow: "٠٣ / المشروعات", developmentsTitle: "أماكن برؤية أوسع.", storyEyebrow: "مشروع مميز", storyTitle: "مدينة داخل المدينة.", smartEyebrow: "٠٤ / الاختيار الأنسب", smartTitle: "مش عارف تبدأ منين؟", smartIntro: "ثلاث اختيارات سريعة لتضييق نطاق البحث.", whyEyebrow: "منهج فانتا", whyTitle: "القرار العقاري يحتاج وضوحًا.", ctaTitle1: "العقار قد يبدو مناسبًا.", ctaTitle2: "المعاينة هي التي تحسم.", ctaText: "انتقل من الاستكشاف إلى الحديث، ثم إلى المكان نفسه." },
    smart: { purpose: "بتشتري ليه؟", live: "للسكن", invest: "للاستثمار", budget: "ميزانيتك؟", where: "فين؟", east: "شرق القاهرة", west: "غرب القاهرة", coastal: "الساحل", matches: "عقارات مناسبة", showMatches: "اعرض العقارات المناسبة", select: "اختر إجابة" },
    why: [ { title: "وضوح السوق", text: "نعرض العقارات بالمعلومات التي تهمك فعلاً." }, { title: "تواصل مباشر", text: "تحدث مباشرة إلى مستشار بخطوة بسيطة." }, { title: "اختيارات منتقاة", text: "ضوضاء أقل وقرارات أفضل." }, { title: "المعاينة أولاً", text: "انتقل من التصفح إلى طلب المعاينة بسرعة." } ],
    pages: { properties: "العقارات", propertiesIntro: "فرص مختارة في أبرز الوجهات المصرية.", developments: "المشروعات", developmentsIntro: "أحياء ومجتمعات برؤية واضحة.", areas: "أطلس المناطق", areasIntro: "قارن الأماكن قبل مقارنة العقارات.", about: "القرار العقاري يحتاج وضوحًا.", aboutIntro: "فانتا تصور لتجربة عقارية أكثر وضوحًا: اكتشف، قارن، عاين، قرر.", contact: "لنبدأ خطوتك القادمة.", contactIntro: "أخبرنا عما تبحث عنه. هذا الموقع التجريبي يجهز رسالة استفسار عبر واتساب.", found: "فرص متاحة", featured: "مجموعة مختارة" },
    detail: { overview: "نظرة عامة", amenities: "المرافق", payment: "خطة السداد", location: "الموقع وما حوله", floor: "مخطط الدور", related: "قد يعجبك أيضًا", interested: "مهتم بهذا العقار؟", inquiryIntro: "شارك بياناتك لتجهيز طلب معاينة عبر واتساب.", name: "الاسم", phone: "رقم الهاتف", date: "الموعد المفضل", send: "المتابعة إلى واتساب", call: "اتصل", gallery: "اعرض ٨ صور", imageNote: "صور تصورّية لأغراض العرض", planNote: "مخطط توضيحي غير مطابق للمقياس", nearby: "أوقات انتقال توضيحية", ground: "الأرضي", first: "الأول", roof: "السطح", galleryTitle: "صور العقار", viewingNote: "لا يتم تخزين طلبات على هذا الموقع التجريبي." },
    about: { steps: [ ["اكتشف", "ابحث عن الأماكن والمنازل المناسبة لتوجهك."], ["قارن", "ضع السعر والمساحة والموقع والتسليم جنبًا إلى جنب."], ["عاين", "شاهد المساحة واسأل عما يهمك."], ["قرر", "اتخذ خطوتك بصورة أوضح."] ], statement: "رحلة عقارية أفضل تبدأ بمعلومات أفضل.", note: "فانتا علامة خيالية لتجربة توضيحية لموقع تسويق عقاري." },
    footer: { line: "عنوانك القادم يبدأ هنا.", navigate: "تصفح", connect: "تواصل", location: "موقعنا", coordinates: "إحداثيات القاهرة", disclaimer: "موقع تجريبي لأغراض عرض التصميم والتطوير. العقارات والأسعار والمشاريع المعروضة بيانات توضيحية وليست عروض بيع حقيقية.", rights: "موقع تصوري. جميع بيانات العقارات خيالية." },
  },
} as const;

export const getCopy = (locale: Locale) => copy[locale];
